spring:
  profiles:
    active: development

---

spring:
  application:
    name: user-management
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8020

---

spring:
  config:
    activate:
      on-profile: development
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb_users;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  sql:
#    init:
#      mode: always
##      schema-locations: classpath:create.sql
#      data-locations: classpath:init.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
eureka:
  client:
      service-url:
        default-zone: http://localhost:8761/eureka
#  cloud:
#    discovery:
#      enabled: false
#eureka:
#  client:
#    enabled: false
#    register-with-eureka: false
#    fetch-registry: false

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgre://user-management-db:8026/users
    username: umuser
    password: uMPassword
