-- Создание схемы, если требуется
CREATE SCHEMA IF NOT EXISTS user_management;

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS user_management._users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    profile_pic_uri VARCHAR(255),
    UNIQUE (username)
    );

-- Создание таблицы ролей
CREATE TABLE IF NOT EXISTS user_management.roles (
     role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
     UNIQUE (name)
    );

-- Создание таблицы для связи пользователей и ролей (многие ко многим)
CREATE TABLE IF NOT EXISTS user_management.user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES _users (user_id),
    FOREIGN KEY (role_id) REFERENCES roles (role_id)
    );

-- Индексы для улучшения производительности запросов
CREATE INDEX IF NOT EXISTS idx_users_username ON user_management._users (username);
CREATE INDEX IF NOT EXISTS idx_roles_name ON user_management.roles (name);