server:
  port: 8080
spring:
  application:
    name: gateway
  #Routes
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalog
            uri: lb://catalog
            predicates:
              - Path=/artists/**
              - Path=/albums/**
              -
            filters:
              - StripPrefix=1
          - id: likes
            uri: lb://likes
            predicates:
              - Path=/likes/**
            filters:
              - StripPrefix=1
          - id: user-management
            uri: lb://user-management
            predicates:
              - Path=/user-management/**
            filters:
              - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
